name: Publish Python Package

on:
  # release:
  #   types: [created]
  push:
    tags:
      - 'v*'       # 匹配v开头的tag
  workflow_dispatch:

permissions:
  id-token: write  # 关键权限！启用OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: production  # 可选环境保护

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://upload.pypi.org/legacy/